### ISSUE TITLE
Unable to start VM

### ISSUE THREAD

**Issue by duckunix** [lstoll/chromeoshack#10]
Pixelbook, On dev, running 67.0.3383.0, not in developer mode.

Trying to start the VM, I get:
```
crosh> vmc list
dev
crosh> vmc start dev
Unable to start VM
crosh> 

```
Anything I can do to help debug, I am will to try.

**Comment by brunoga** [comment]
Try "vmc stop dev" then "vmc start dev" again.

If you do not mind starting form scratch:

vmc stop dev
vmc destroy dev
vmc start dev

**Comment by duckunix** [comment]
That worked.  I got in.  Now, I get to figure out what to do next.
