### ISSUE TITLE
README should specify whether --container_name is a label or a selector

### ISSUE THREAD

**Issue by sowbug** [lstoll/chromeoshack#13]
https://github.com/lstoll/cros-crostini/blob/master/README.md

> Launch a container run_container.sh --container_name=stretch --user=<username> --shell
> You're now inside a stretch environment

Because the arg to `--container_name` matches the "inside a ___ environment" text, it's hard to know whether `--container_name` is an arbitrary label you give your container, or whether it tells which kind of environment will be created. I can't quite tell, either, from my own experimentation. It'd be nice to be more explicit about this, either by changing the example to `mystretchcontainer` or by explaining that `stretch` is one of N enumerated choices (and including a description of how to see those choices).

**Comment by DennisLfromGA** [comment]
Agree, I'm new to this and still figuring it all out.  Luckily, a link to [run_container.sh](https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/master/project-termina/chromeos-base/termina-lxd-scripts/files/run_container.sh) was given further down in the README section: 'Some notable things to look at'

Examining the [script](https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/master/project-termina/chromeos-base/termina-lxd-scripts/files/run_container.sh#14) shows 'container_name' is baked-in and not arbitrary. 

Once that script is run it adds the 'google:' images remote url so you can see what's available by entering:

`lxc image list google:`


-**DennisLfromGA**

**Comment by sowbug** [comment]
Ah yes, reading the source! Cool, that makes sense. So maybe this bug can change to documenting `lxc image list google:` somewhere in the README. That'll be enough for the lazy but inquisitive like me to figure it out.
