### ISSUE TITLE
how to access folders om the host from the containres?

### ISSUE THREAD

**Issue by ukabu** [lstoll/chromeoshack#15]
With Crouton, we can easily access the host ~/Download folder and setup other folder to be shared from the host and the chroot.

How can we do that with crostini containers?

**Comment by AlexLewandowski** [comment]
I don't think this is currently possible, but I could be wrong. 

In the meantime, I'm using syncthing to sync a folder between the container and the pixelbook. Syncthing can be installed on the pixelbook natively, either through the package manager in termux or the Syncthing android app.

**Comment by cliveb** [comment]
In light of Meltdown and Spectre maybe the Linux Control Groups API is timely for ChromeOS. Hopefully a test bed for Capability-based security. https://lwn.net/Articles/679786/
