### ISSUE TITLE
Won't be available on Beta channel until 67

### ISSUE THREAD

**Issue by llamadonica** [lstoll/chromeoshack#4]
Running `vmc ...` after setting `--enable-features=Crostini` gives me the message:
`ERROR: command 'vmc' is not available`

Some digging led me to [this commit](https://chromium-review.googlesource.com/c/chromium/src/+/985143/1/chrome/browser/chromeos/virtual_machines/virtual_machines_util.cc#34).

So for future testers, I think this is by design: it's not available in beta until m67.

**Comment by bttnns** [comment]
I'm on beta channel w/ pixelbook.  I set the Crostini flag @ chrome://flags (search crostini (not sure if it matters though)) and set the conf file, and vmc works.

**Comment by lstoll** [comment]
This CL is about feature flagging, not actually including the code. The beta channel should have the basics in there, and it seems to be working for some.

That CL landing seems to show that the next dev channel update will have this working out of the box, without having to put it in to developer mode/hack in the flag. That'll be nice.
