### ISSUE TITLE
vmc: command not found

### ISSUE THREAD

**Issue by Marshall126** [lstoll/chromeoshack#9]
I'm in dev channel version 67 and crostini is enabled in chrome://flags

**Comment by ustomerus** [comment]
The command is seen by the OS, but not allowed, which according [this](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-reviews/2CAECU5G44Y) page means the Crostini feature isn't enabled. Any way to enable it other than the flag?

**Comment by kzahel** [comment]
use the vmc command from the `crosh>` prompt, not after typing `shell`

**Comment by ustomerus** [comment]
Been doing that. 
ERROR: command 'vmc' is not available. 
This is different from the usual "Command not found," meaning that I simply do not have permissions to access the command. Currently on latest dev build, 67.0.3383.0

**Comment by HacDan** [comment]
I'm experiencing the same thing. Dev channel: 
Version 67.0.3383.0 (Official Build) dev (64-bit) HP Chromebook 14 G4

I've enabled both flags for Container Support and Crostini support, but that didn't change anything. 

Is this restricted to certain devices?

**Comment by kzahel** [comment]
AFAIK this is pixelbook only

**Comment by lstoll** [comment]
I'm 99% sure this will currently only work on pixelbooks.

**Comment by vjvalenti2** [comment]
Any word on when this will be opened up to the rest of the Intel Chromebooks that support hardware virtualization?

**Comment by kennwhite** [comment]
Not working on Samsung Chromebook 3 either (dev mode + dev channel + `--enable-features=Crostini,CrOSContainer,ExperimentalCrostiniUI`). No vsh from shell (and missing `/dev/kvm`), or vmc in crosh, though shell (as root) allows `run_oci`. Based on the [ChromeOS commits](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-reviews/2CAECU5G44Y) referenced above, and from this [Reddit thread](https://www.reddit.com/r/PixelBook/comments/7zxz57/howto_boot_a_ubuntu_vm_using_crosvm/), looks like it's coming soon, but currently restricted to PixelBooks for dogfooding. Rumor has it the wider roll out will be tied to Google IO announcement in early May.

**Comment by gregorydillon** [comment]
Toshiba CB 2, likewise give message command not available, which is unique compared the the usual "unknown command" response.
![screenshot 2018-04-05 at 8 00 11 am](https://user-images.githubusercontent.com/5195087/38374042-94ec61bc-38a7-11e8-83fb-081c057a18d6.png)

**Comment by kennwhite** [comment]
Good news is it looks like there has been active development this year to enable crosvm on non-Pixelbooks, including lower end x64 Intel CPUs (like the 4-core Celeron N3150 Braswell, used on some Asus, Acer, and Lenovo Chromebooks): https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/936323

**Comment by navigaid** [comment]
@gregorydillon https://chromium-review.googlesource.com/c/chromiumos/platform2/+/875163
You probably need to manually comment out these lines.
BTW, someone did that already, https://www.reddit.com/r/PixelBook/comments/7zxz57/howto_boot_a_ubuntu_vm_using_crosvm/dutwcwv/
